```{r}
#Counts of total number of busses
total_buses = full_dataset %>% 
  filter(!(route_short_name %in% c("WEST", "NORTH","SOUTH", "EAST"))) %>% 
  group_by(route_short_name) %>% 
  summarise(total_counts = n()) %>% 
  filter(total_counts > 20)

#Cancelled bus proportion
cancelled_buses_proportion = cancelled_buses %>% 
  left_join(total_buses, by = "route_short_name") %>% 
  mutate(Cancelled_Proportion = Tally/total_counts) %>% 
  select(route_short_name, Cancelled_Proportion) %>% 
  arrange(desc(Cancelled_Proportion)) %>% 
  filter(is.na(route_short_name) != TRUE) %>% 
  #This is just to get the ordering we want in the barplot, can remove later on
  mutate(Position = factor(route_short_name, route_short_name))

print(cancelled_buses_proportion)

#Showing the cancelled bus proportion in a graph 
ggplot(cancelled_buses_proportion, aes(x = Position, y = Cancelled_Proportion)) + 
  geom_col() +
  theme_minimal()+
  coord_flip() + 
  theme(axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(hjust = 0.5, face = "bold")) + 
  ylab("") +
  ggtitle("Proportion of bus cancellation")+ 
  xlab("Bus routes") +
  scale_y_continuous(expand = expansion(c(0,0.05)))

```

```{r}
#BUS CANCELLATION BY DAY 

#Getting the cancelled buses information 
cancelled_buses_day = subset(full_dataset, is.na(cancelled) == FALSE) %>% filter(!(route_short_name %in% c("WEST", "NORTH","SOUTH", "EAST"))) %>% group_by(day_of_week) %>% summarise(Tally = n()) 

total_buses_day = full_dataset %>% 
  filter(!(route_short_name %in% c("WEST", "NORTH","SOUTH", "EAST"))) %>% 
  group_by(day_of_week) %>% 
  summarise(total_counts = n()) 

#Cancelled bus proportion
cancelled_buses_day_proportion = cancelled_buses_day %>% 
  left_join(total_buses_day, by = "day_of_week") %>% 
  mutate(Cancelled_Proportion = Tally/total_counts) %>% 
  select(day_of_week, Cancelled_Proportion) %>% 
  arrange(desc(Cancelled_Proportion)) %>% 
  filter(is.na(day_of_week) != TRUE) %>% 
  #This is just to get the ordering we want in the barplot, can remove later on
  mutate(Position = factor(day_of_week, day_of_week))

#Showing the cancelled bus proportion in a graph 
ggplot(cancelled_buses_day_proportion, aes(x = Position, y = Cancelled_Proportion)) + 
  geom_col() +
  theme_minimal()+
  coord_flip() + 
  theme(axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(hjust = 0.5, face = "bold")) + 
  ylab("") +
  ggtitle("Proportion of bus cancellation by day")+ 
  xlab("Day of week") +
  scale_y_continuous(expand = expansion(c(0,0.05)))
```


```{r}
#We have a row of outliers

#We had one observation that was -75000 minutes. Really skeptical so this was removed 
ggplot(non_cancelled %>% filter(delay > -75000), mapping = aes(x = day_of_week, y = delay)) + geom_boxplot()

ggplot(non_cancelled %>% filter(delay > -75000), mapping = aes(x = day_of_week, y = delay)) + geom_boxplot() + xlab("Day of week")

ggplot(non_cancelled %>% filter(delay > -75000 & time_frame %in% c(21,22,23)), mapping = aes(x = time_frame, y = delay)) + geom_boxplot() + xlab("Hour of the day")
```
