---
title: "Bus_Data_Extraction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(warn=-1)
```

```{r eval=FALSE}
# Load libraries
library(tidyverse)
library(jsonlite)
library(httr)
```

```{r}
# Obtain AT API Key
AT_key = "567bb1fb7ab64582905c7812648075e1"

# Get today's date
todays_date = as.character(Sys.Date())

# Saving folder structures
wd_main = getwd()
wd_rawdata = paste(wd_main, '/rawdata', sep = "")
wd_businfo = paste(wd_rawdata, '/businfo', sep = "")
wd_busarrivals = paste(wd_rawdata, '/busarrivals', sep = "")
```

```{r}
setwd(paste(wd_rawdata, '/businfo', sep = ""))

# Reading in bus static files 
stops = read.table("stops.txt", header = TRUE, sep = ",", quote = "")
stop_times = read.table("stop_times.txt", header = TRUE, sep = ",", quote = "")
trips = read.table("trips.txt", header = TRUE, sep = ",", quote = ",", fill = TRUE)
routes = read.table("routes.txt", header = TRUE, sep = ",", quote = "")
shapes = read.table("shapes.txt", header = TRUE, sep = ",", quote = "")
stop_times = stop_times %>% mutate(stop_code = substring(stop_id, 1, regexpr("-", stop_id)[1] - 1))
```

```{r}
# Grabbing live bus arrival data for current day

combined_feed <- tryCatch(
  GET('https://api.at.govt.nz/realtime/legacy/',
      accept_json(),
      add_headers('Ocp-Apim-Subscription-Key' = AT_key)),
  error=function(e) NULL)

vehicle <- tryCatch(
  GET('https://api.at.govt.nz/realtime/legacy/vehiclelocations',
      accept_json(),
      add_headers('Ocp-Apim-Subscription-Key' = AT_key)),
  error=function(e) NULL)

trip_updates <- tryCatch(
  GET('https://api.at.govt.nz/realtime/legacy/tripupdates',
      accept_json(),
      add_headers('Ocp-Apim-Subscription-Key' = AT_key)),
  error=function(e) NULL)

alerts <- tryCatch(
  GET('https://api.at.govt.nz/realtime/legacy/servicealerts',
      accept_json(),
      add_headers('Ocp-Apim-Subscription-Key' = AT_key)),
  error=function(e) NULL)
```


```{r}
# Saving data to JSON file
setwd(wd_busarrivals)
dir.create(todays_date)
setwd(paste(wd_busarrivals, paste('/', todays_date, sep = ""), sep = ""))

write_json(content(vehicle), paste('vehicle_', todays_date), pretty = TRUE)
write_json(content(combined_feed), paste('combined_', todays_date), pretty = TRUE)
write_json(content(trip_updates), paste('tripupdates_', todays_date), pretty = TRUE)
write_json(content(alerts), paste('alerts_', todays_date), pretty = TRUE)
```

```{r include=FALSE}
trip_content = content(trip_updates)[[2]][[2]]

head(trip_content)
length(trip_content)
#trip_content = temp[[2]][[2]]
#head(str(trip_content), level = 3)

#Helper Functions
null_check = function(x) if(is.null(x)) NA else x

trips = trips %>% filter(trip_id != "trip_id")

trip_data = as.data.frame(do.call(rbind, lapply(trip_content, 
                                                function(x) c(null_check(x$trip_update$trip$trip_id),
                                                              null_check(x$trip_update$trip$direction_id),
                                                              null_check(x$trip_update$trip$route_id),
                                                              null_check(x$trip_update$stop_time_update$stop_id),
                                                              null_check(x$trip_update$trip$schedule_relationship),
                                                              null_check(x$trip_update$delay), 
                                                              null_check(x$trip_update$stop_time_update$stop_sequence),
                                                              null_check(x$trip_update$stop_time_update$arrival$time),
                                                              null_check(x$trip_update$stop_time_update$arrival$delay),
                                                              null_check(x$trip_update$stop_time_update$departure$time),
                                                              null_check(x$trip_update$stop_time_update$departure$delay)
                                                ))))
# Setting column names
colnames(trip_data) = c("trip_id", 
                        "direction_id", 
                        "route_id", 
                        "stop_id", 
                        "schedule_relationship", 
                        "delay", 
                        "stop_sequence", 
                        "act_arrival_time", 
                        "arrival_delay", 
                        "act_departure_time", 
                        "act_departure_delay")

# Fixing stop sequence type
trip_data$stop_sequence = as.integer(trip_data$stop_sequence)
```

```{r}
#Now alerts are different 
alert_contents = content(alerts)

alert_data = as.data.frame(do.call(rbind, lapply(alert_contents[[2]][[2]], function(x) c(n(x$id), n(x$alert$effect), n(x$alert$header_text$translation[[1]]$text), n(x$alert$informed_entity[[1]]$trip$trip_id)))))

colnames(alert_data) = c("id", "effect", "text", "trip_id")
alert_temp1 = alert_data

View(alert_contents)

alert_temp1$trip_id = ifelse(alert_temp1$trip_id == alert_temp1$id, NA, alert_temp1$trip_id)
cancelled_buses = alert_temp1 %>% filter(is.na(trip_id) == FALSE) %>% select(trip_id) %>% mutate(cancelled = TRUE)

cancelled_data = alert_data %>% filter(effect == "NO_SERVICE")
#Then filter about by cancellation 
#These are buses that have have cancelled prior to the event
#Could have alsued used the description text and found Trip Cancelled. 
cancelled_data = cancelled_data %>% filter(grepl("Cancellation", text) == TRUE) %>% select(trip_id) %>% mutate(cancelled = TRUE)
```


```{r}
# Join all tables to collate full dataset

bus_arrivals_full = trip_data %>% 
  left_join(stop_times %>% select("trip_id", "stop_sequence", "arrival_time", "departure_time"), 
            by = c("trip_id" = "trip_id", "stop_sequence" = "stop_sequence")) %>%
  left_join(stops %>% select("stop_id", "stop_lat", "stop_lon"), 
            by = c("stop_id" = "stop_id")) %>%
  left_join(routes %>% select("route_id", "route_short_name"), 
            by = c("route_id" = "route_id")) %>% 
  left_join(cancelled_buses, 
            by = c("trip_id" = "trip_id"))
```











