---
title: "Weather-Data-Collection"
output: html_document
---

# This is intialisation. Just have a play around 

```{r}
#Initialisation
library(httr)

#Also free API, I can only make max 1million calls to API, be mindful of that though 1million LOL that's enough
api_key <- "d0d5efa738a7493db8a61211231203"
```

```{r}
#Location we can give latitude,longitude 
location <- "Auckland"
#location = "48.8567,2.3508" 

#Also for the start date can only get previous 7 days be mindful of that

#Format is yyyy-mm-dd
start_date <- "2023-05-02"
```

```{r}
response <- GET(paste0("https://api.weatherapi.com/v1/history.json?key=", api_key, "&q=", location, "&dt=", start_date))
```

```{r}
weather_data <- content(response, "parsed")
```

```{r}
#https://www.weatherapi.com/api-explorer.aspx look at this, shows what data will look like

#Collects hourly data, and has lots of information
class(weather_data)
saveRDS(weather_data, file="weather.RData")
```


# Function to get weather data for a specific

```{r}

#Takes in a suburb, lat, lon and date. Suburb is just used 
weather_data = function(suburb = "", lat = NA, lon = NA, date) {
  #Location we can give latitude,longitude 
  
  if (is.na(lat) | is.na(lon)) {
    location <- suburb
  } else if (suburb == "") {
    stop("Need to input valid suburb, or valid latitude and longitude")
  } else {
    location <- paste(lat, ",", lon, sep = "")
  }
  
  #Also for the start date can only get previous 7 days be mindful of that
  
  #Format is yyyy-mm-dd
  start_date <- date
  
  #Getting data from API
  response <- GET(paste0("https://api.weatherapi.com/v1/history.json?key=", api_key, "&q=", location, "&dt=", start_date))
  
  #Getting contents from JSON file
  weather_data <- content(response, "parsed")
  
  #Set file path and name (currently doing local directory, with date-suburb.rds)
  weather_file_location = paste(date, "-", suburb, ".rds", sep = "")
  
  #Save the file into directory
  saveRDS(weather_data, file=weather_file_location)
}
```

```{r}
#Locations of interest dataset 

#Didn't know where to put Mangere so chucked it here for now 

west = c("Massey", "Henderson", "Glen Eden", "New Lynn", "Avondale", "Mount Roskill", "Mangere")
west_lat = c(-36.83, -36.88, -36.91, -36.91, -36.89, -36.92, -36.97)
west_lon = c(174.62,  174.63, 174.64, 174.68, 174.69, 174.73, 174.79)

west.df = data.frame(suburb = west, lat = west_lat, lon = west_lon)

north = c("Albany", "Rosedale", "Wairau Valley", "Glenfield", "Takapuna")
north_lat = c(-36.73, -36.75, -36.77, -36.78, -36.79)
north_lon = c(174.70, 174.71, 174.74, 174.72, 174.77)

north.df = data.frame(suburb = north, lat = north_lat, lon = north_lon)

east = c("Howick", "East Tamaki", "Flat Bush")
east_lat = c(-36.89, -36.94, -36.97)
east_lon = c(174.92, 174.89, 174.92)

east.df = data.frame(suburb = east, lat = east_lat, lon = east_lon)

south = c("Otahuhu", "Papatoetoe", "Manukau City Centre", "Maurewa", "Papakura")
south_lat = c(-36.95, -36.97, -36.99, -37.02, -37.06)
south_lon = c(174.85, 174.86, 174.87, 174.89, 174.95)

south.df = data.frame(suburb = south, lat = south_lat, lon = south_lon)

#Note St Heliers isn't like a big city, but needed a city that was around that area
central = c("Auckland CBD", "Grey Lynn", "New Market", "Mount Eden", "Remuera", "Epsom", "Onehunga", "Penrose", "Ellerslie", "Mount Wellington", "St Heliers")
central_lat = c(-36.85, -36.86, -36.87,-36.89, -36.88, -36.89, -36.92, -36.92, -36.90, -36.91, -36.86)
central_lon = c(174.76,174.74, 174.78, 174.75, 174.80, 174.77, 174.79, 174.82, 174.82, 174.84, 174.86)

central.df = data.frame(suburb = central, lat = central_lat, lon = central_lon)
```

# TO GET DATASET USE CODE BELOW

```{r}
library(httr)
library(jsonlite)
#Apply function to every row of the dataset - use apply function.

collection_date = "2023-04-29"

#Please put the city or suburb you want to do
suburb_df =  central.df

donwload_data <- apply(suburb_df, 1, function(x) {
  weather_data(x[["suburb"]],x[["lat"]], x[["lon"]], date = collection_date)
})

```

# Feel free to ignore
```{r}
#So this is just a trial, I just wanted to see if the rds files that we are collect has all the hours. It does! 
trial = readRDS("2023-04-29-East Tamaki.rds")

time = vector(mode = "character", length = 0)
for (i in seq_along(trial$forecast$forecastday[[1]]$hour)) {
  time <- c(time, trial$forecast$forecastday[[1]]$hour[[i]]$time)
}
print(time)
```













